version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: cms_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cms_db
      POSTGRES_USER: cms_user
      POSTGRES_PASSWORD: cms_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - cms_network

  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cms_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage/app/public:/var/www/html/storage/app/public
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=cms_db
      - DB_USERNAME=cms_user
      - DB_PASSWORD=cms_password
    depends_on:
      - postgres
    networks:
      - cms_network

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: cms_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - cms_network


volumes:
  postgres_data:
    driver: local

networks:
  cms_network:
    driver: bridge
